// Generated by scripts/buildGezekAssets.ts. Do not edit.
export const PRODUCTION_ASSET_INDEX = {
  "artwork": {
    "event/concert-classical-acoustic/v01": {
      "Hero": "svg/artwork/event/concert-classical-acoustic/v01/hero.svg",
      "Square": "svg/artwork/event/concert-classical-acoustic/v01/square.svg",
      "Compact": "svg/artwork/event/concert-classical-acoustic/v01/compact.svg"
    },
    "event/concert-live/v01": {
      "Hero": "svg/artwork/event/concert-live/v01/hero.svg",
      "Square": "svg/artwork/event/concert-live/v01/square.svg",
      "Compact": "svg/artwork/event/concert-live/v01/compact.svg"
    },
    "event/creative-workshop/v01": {
      "Hero": "svg/artwork/event/creative-workshop/v01/hero.svg",
      "Square": "svg/artwork/event/creative-workshop/v01/square.svg",
      "Compact": "svg/artwork/event/creative-workshop/v01/compact.svg"
    },
    "event/culinary-workshop/v01": {
      "Hero": "svg/artwork/event/culinary-workshop/v01/hero.svg",
      "Square": "svg/artwork/event/culinary-workshop/v01/square.svg",
      "Compact": "svg/artwork/event/culinary-workshop/v01/compact.svg"
    },
    "event/exhibition-opening/v01": {
      "Hero": "svg/artwork/event/exhibition-opening/v01/hero.svg",
      "Square": "svg/artwork/event/exhibition-opening/v01/square.svg",
      "Compact": "svg/artwork/event/exhibition-opening/v01/compact.svg"
    },
    "event/family-show/v01": {
      "Hero": "svg/artwork/event/family-show/v01/hero.svg",
      "Square": "svg/artwork/event/family-show/v01/square.svg",
      "Compact": "svg/artwork/event/family-show/v01/compact.svg"
    },
    "event/festival-food-drink/v01": {
      "Hero": "svg/artwork/event/festival-food-drink/v01/hero.svg",
      "Square": "svg/artwork/event/festival-food-drink/v01/square.svg",
      "Compact": "svg/artwork/event/festival-food-drink/v01/compact.svg"
    },
    "event/film-talk/v01": {
      "Hero": "svg/artwork/event/film-talk/v01/hero.svg",
      "Square": "svg/artwork/event/film-talk/v01/square.svg",
      "Compact": "svg/artwork/event/film-talk/v01/compact.svg"
    },
    "event/sports-event/v01": {
      "Hero": "svg/artwork/event/sports-event/v01/hero.svg",
      "Square": "svg/artwork/event/sports-event/v01/square.svg",
      "Compact": "svg/artwork/event/sports-event/v01/compact.svg"
    },
    "event/standup-comedy/v01": {
      "Hero": "svg/artwork/event/standup-comedy/v01/hero.svg",
      "Square": "svg/artwork/event/standup-comedy/v01/square.svg",
      "Compact": "svg/artwork/event/standup-comedy/v01/compact.svg"
    },
    "event/theatre-play/v01": {
      "Hero": "svg/artwork/event/theatre-play/v01/hero.svg",
      "Square": "svg/artwork/event/theatre-play/v01/square.svg",
      "Compact": "svg/artwork/event/theatre-play/v01/compact.svg"
    },
    "event/trivia-games/v01": {
      "Hero": "svg/artwork/event/trivia-games/v01/hero.svg",
      "Square": "svg/artwork/event/trivia-games/v01/square.svg",
      "Compact": "svg/artwork/event/trivia-games/v01/compact.svg"
    },
    "experience/xp-altinkoy-koy-yasamini-uc-izden-oku/hero-v1": {
      "Hero": "svg/artwork/experience/xp-altinkoy-koy-yasamini-uc-izden-oku/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-altinkoy-koy-yasamini-uc-izden-oku/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-altinkoy-koy-yasamini-uc-izden-oku/hero-v1/compact.svg"
    },
    "experience/xp-altinpark-uzun-ogleden-sonra/hero-v1": {
      "Hero": "svg/artwork/experience/xp-altinpark-uzun-ogleden-sonra/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-altinpark-uzun-ogleden-sonra/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-altinpark-uzun-ogleden-sonra/hero-v1/compact.svg"
    },
    "experience/xp-anadolu-kronolojik/hero-v1": {
      "Hero": "svg/artwork/experience/xp-anadolu-kronolojik/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-anadolu-kronolojik/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-anadolu-kronolojik/hero-v1/compact.svg"
    },
    "experience/xp-anitkabir-maltepe/hero-v1": {
      "Hero": "svg/artwork/experience/xp-anitkabir-maltepe/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-anitkabir-maltepe/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-anitkabir-maltepe/hero-v1/compact.svg"
    },
    "experience/xp-ankara-palas-ikinci-tbmm/hero-v1": {
      "Hero": "svg/artwork/experience/xp-ankara-palas-ikinci-tbmm/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-ankara-palas-ikinci-tbmm/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-ankara-palas-ikinci-tbmm/hero-v1/compact.svg"
    },
    "experience/xp-aoc-kurulus-hikayesi/hero-v1": {
      "Hero": "svg/artwork/experience/xp-aoc-kurulus-hikayesi/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-aoc-kurulus-hikayesi/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-aoc-kurulus-hikayesi/hero-v1/compact.svg"
    },
    "experience/xp-aqua-vega-uc-yasam-alani/hero-v1": {
      "Hero": "svg/artwork/experience/xp-aqua-vega-uc-yasam-alani/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-aqua-vega-uc-yasam-alani/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-aqua-vega-uc-yasam-alani/hero-v1/compact.svg"
    },
    "experience/xp-arslanhane-alaaddin-selcuklu/hero-v1": {
      "Hero": "svg/artwork/experience/xp-arslanhane-alaaddin-selcuklu/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-arslanhane-alaaddin-selcuklu/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-arslanhane-alaaddin-selcuklu/hero-v1/compact.svg"
    },
    "experience/xp-aspava-ikram-ritueli/hero-v1": {
      "Hero": "svg/artwork/experience/xp-aspava-ikram-ritueli/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-aspava-ikram-ritueli/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-aspava-ikram-ritueli/hero-v1/compact.svg"
    },
    "experience/xp-beypazari-halfday/hero-v1": {
      "Hero": "svg/artwork/experience/xp-beypazari-halfday/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-beypazari-halfday/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-beypazari-halfday/hero-v1/compact.svg"
    },
    "experience/xp-bogazici-ulus-ogle-ritueli/hero-v1": {
      "Hero": "svg/artwork/experience/xp-bogazici-ulus-ogle-ritueli/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-bogazici-ulus-ogle-ritueli/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-bogazici-ulus-ogle-ritueli/hero-v1/compact.svg"
    },
    "experience/xp-bolu-akin-eski-garajlar-tencere/hero-v1": {
      "Hero": "svg/artwork/experience/xp-bolu-akin-eski-garajlar-tencere/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-bolu-akin-eski-garajlar-tencere/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-bolu-akin-eski-garajlar-tencere/hero-v1/compact.svg"
    },
    "experience/xp-botanik-atakule-short/hero-v1": {
      "Hero": "svg/artwork/experience/xp-botanik-atakule-short/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-botanik-atakule-short/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-botanik-atakule-short/hero-v1/compact.svg"
    },
    "experience/xp-cengelhan-teknolojinin-izini-sur/hero-v1": {
      "Hero": "svg/artwork/experience/xp-cengelhan-teknolojinin-izini-sur/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-cengelhan-teknolojinin-izini-sur/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-cengelhan-teknolojinin-izini-sur/hero-v1/compact.svg"
    },
    "experience/xp-cin-ali-iki-kusak/hero-v1": {
      "Hero": "svg/artwork/experience/xp-cin-ali-iki-kusak/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-cin-ali-iki-kusak/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-cin-ali-iki-kusak/hero-v1/compact.svg"
    },
    "experience/xp-cubuk-1-baraji-muhendislik-gozu/hero-v1": {
      "Hero": "svg/artwork/experience/xp-cubuk-1-baraji-muhendislik-gozu/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-cubuk-1-baraji-muhendislik-gozu/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-cubuk-1-baraji-muhendislik-gozu/hero-v1/compact.svg"
    },
    "experience/xp-da-vinci-yeni-oyun/hero-v1": {
      "Hero": "svg/artwork/experience/xp-da-vinci-yeni-oyun/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-da-vinci-yeni-oyun/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-da-vinci-yeni-oyun/hero-v1/compact.svg"
    },
    "experience/xp-dikmen-vadisi-kot-yuruyusu/hero-v1": {
      "Hero": "svg/artwork/experience/xp-dikmen-vadisi-kot-yuruyusu/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-dikmen-vadisi-kot-yuruyusu/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-dikmen-vadisi-kot-yuruyusu/hero-v1/compact.svg"
    },
    "experience/xp-dost-konu-raf-haritasi/hero-v1": {
      "Hero": "svg/artwork/experience/xp-dost-konu-raf-haritasi/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-dost-konu-raf-haritasi/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-dost-konu-raf-haritasi/hero-v1/compact.svg"
    },
    "experience/xp-duveroglu-lahmacun/hero-v1": {
      "Hero": "svg/artwork/experience/xp-duveroglu-lahmacun/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-duveroglu-lahmacun/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-duveroglu-lahmacun/hero-v1/compact.svg"
    },
    "experience/xp-erimtan-kale/hero-v1": {
      "Hero": "svg/artwork/experience/xp-erimtan-kale/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-erimtan-kale/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-erimtan-kale/hero-v1/compact.svg"
    },
    "experience/xp-etnografya-resim/hero-v1": {
      "Hero": "svg/artwork/experience/xp-etnografya-resim/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-etnografya-resim/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-etnografya-resim/hero-v1/compact.svg"
    },
    "experience/xp-eymir-bisikletle-dolas/hero-v1": {
      "Hero": "svg/artwork/experience/xp-eymir-bisikletle-dolas/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-eymir-bisikletle-dolas/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-eymir-bisikletle-dolas/hero-v1/compact.svg"
    },
    "experience/xp-eymir-halfday/hero-v1": {
      "Hero": "svg/artwork/experience/xp-eymir-halfday/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-eymir-halfday/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-eymir-halfday/hero-v1/compact.svg"
    },
    "experience/xp-federal-bilkent-demleme/hero-v1": {
      "Hero": "svg/artwork/experience/xp-federal-bilkent-demleme/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-federal-bilkent-demleme/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-federal-bilkent-demleme/hero-v1/compact.svg"
    },
    "experience/xp-goksu-loop/hero-v1": {
      "Hero": "svg/artwork/experience/xp-goksu-loop/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-goksu-loop/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-goksu-loop/hero-v1/compact.svg"
    },
    "experience/xp-gokyay-satranc-taslari/hero-v1": {
      "Hero": "svg/artwork/experience/xp-gokyay-satranc-taslari/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-gokyay-satranc-taslari/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-gokyay-satranc-taslari/hero-v1/compact.svg"
    },
    "experience/xp-gordion-halfday/hero-v1": {
      "Hero": "svg/artwork/experience/xp-gordion-halfday/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-gordion-halfday/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-gordion-halfday/hero-v1/compact.svg"
    },
    "experience/xp-hacibayram-augustus/hero-v1": {
      "Hero": "svg/artwork/experience/xp-hacibayram-augustus/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-hacibayram-augustus/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-hacibayram-augustus/hero-v1/compact.svg"
    },
    "experience/xp-hanem-konya-sofrasi/hero-v1": {
      "Hero": "svg/artwork/experience/xp-hanem-konya-sofrasi/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-hanem-konya-sofrasi/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-hanem-konya-sofrasi/hero-v1/compact.svg"
    },
    "experience/xp-hava-kuvvetleri-iki-saat/hero-v1": {
      "Hero": "svg/artwork/experience/xp-hava-kuvvetleri-iki-saat/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-hava-kuvvetleri-iki-saat/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-hava-kuvvetleri-iki-saat/hero-v1/compact.svg"
    },
    "experience/xp-kecioren-cocuk-sanat-muzesi-rehber/hero-v1": {
      "Hero": "svg/artwork/experience/xp-kecioren-cocuk-sanat-muzesi-rehber/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-kecioren-cocuk-sanat-muzesi-rehber/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-kecioren-cocuk-sanat-muzesi-rehber/hero-v1/compact.svg"
    },
    "experience/xp-kelime-erimtan-kale/hero-v1": {
      "Hero": "svg/artwork/experience/xp-kelime-erimtan-kale/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-kelime-erimtan-kale/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-kelime-erimtan-kale/hero-v1/compact.svg"
    },
    "experience/xp-kitir-tunali-bulusma-hafizasi/hero-v1": {
      "Hero": "svg/artwork/experience/xp-kitir-tunali-bulusma-hafizasi/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-kitir-tunali-bulusma-hafizasi/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-kitir-tunali-bulusma-hafizasi/hero-v1/compact.svg"
    },
    "experience/xp-kizilcahamam-halfday/hero-v1": {
      "Hero": "svg/artwork/experience/xp-kizilcahamam-halfday/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-kizilcahamam-halfday/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-kizilcahamam-halfday/hero-v1/compact.svg"
    },
    "experience/xp-kugulu-segmenler/hero-v1": {
      "Hero": "svg/artwork/experience/xp-kugulu-segmenler/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-kugulu-segmenler/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-kugulu-segmenler/hero-v1/compact.svg"
    },
    "experience/xp-mavi-gol-sehirden-uzak/hero-v1": {
      "Hero": "svg/artwork/experience/xp-mavi-gol-sehirden-uzak/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-mavi-gol-sehirden-uzak/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-mavi-gol-sehirden-uzak/hero-v1/compact.svg"
    },
    "experience/xp-meclis-duo-short/hero-v1": {
      "Hero": "svg/artwork/experience/xp-meclis-duo-short/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-meclis-duo-short/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-meclis-duo-short/hero-v1/compact.svg"
    },
    "experience/xp-millet-kutuphanesi-derin-calisma/hero-v1": {
      "Hero": "svg/artwork/experience/xp-millet-kutuphanesi-derin-calisma/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-millet-kutuphanesi-derin-calisma/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-millet-kutuphanesi-derin-calisma/hero-v1/compact.svg"
    },
    "experience/xp-mogan-halfday/hero-v1": {
      "Hero": "svg/artwork/experience/xp-mogan-halfday/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-mogan-halfday/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-mogan-halfday/hero-v1/compact.svg"
    },
    "experience/xp-no29-kahve-tatli/hero-v1": {
      "Hero": "svg/artwork/experience/xp-no29-kahve-tatli/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-no29-kahve-tatli/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-no29-kahve-tatli/hero-v1/compact.svg"
    },
    "experience/xp-odtu-double-museum/hero-v1": {
      "Hero": "svg/artwork/experience/xp-odtu-double-museum/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-odtu-double-museum/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-odtu-double-museum/hero-v1/compact.svg"
    },
    "experience/xp-old-school-iki-demleme/hero-v1": {
      "Hero": "svg/artwork/experience/xp-old-school-iki-demleme/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-old-school-iki-demleme/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-old-school-iki-demleme/hero-v1/compact.svg"
    },
    "experience/xp-pecenek-iskitler-doner-ritueli/hero-v1": {
      "Hero": "svg/artwork/experience/xp-pecenek-iskitler-doner-ritueli/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-pecenek-iskitler-doner-ritueli/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-pecenek-iskitler-doner-ritueli/hero-v1/compact.svg"
    },
    "experience/xp-ptt-pullardan-donem-oku/hero-v1": {
      "Hero": "svg/artwork/experience/xp-ptt-pullardan-donem-oku/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-ptt-pullardan-donem-oku/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-ptt-pullardan-donem-oku/hero-v1/compact.svg"
    },
    "experience/xp-roma-meclis/hero-v1": {
      "Hero": "svg/artwork/experience/xp-roma-meclis/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-roma-meclis/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-roma-meclis/hero-v1/compact.svg"
    },
    "experience/xp-sakarya-muharebesini-araziden-oku/hero-v1": {
      "Hero": "svg/artwork/experience/xp-sakarya-muharebesini-araziden-oku/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-sakarya-muharebesini-araziden-oku/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-sakarya-muharebesini-araziden-oku/hero-v1/compact.svg"
    },
    "experience/xp-tragos-tanitim-dersi/hero-v1": {
      "Hero": "svg/artwork/experience/xp-tragos-tanitim-dersi/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-tragos-tanitim-dersi/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-tragos-tanitim-dersi/hero-v1/compact.svg"
    },
    "experience/xp-trilye-balik/hero-v1": {
      "Hero": "svg/artwork/experience/xp-trilye-balik/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-trilye-balik/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-trilye-balik/hero-v1/compact.svg"
    },
    "experience/xp-tunali-kugulu-short/hero-v1": {
      "Hero": "svg/artwork/experience/xp-tunali-kugulu-short/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-tunali-kugulu-short/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-tunali-kugulu-short/hero-v1/compact.svg"
    },
    "experience/xp-ulucanlar-hamamonu/hero-v1": {
      "Hero": "svg/artwork/experience/xp-ulucanlar-hamamonu/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-ulucanlar-hamamonu/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-ulucanlar-hamamonu/hero-v1/compact.svg"
    },
    "experience/xp-urumci-on-cebeci-uygur-sofrasi/hero-v1": {
      "Hero": "svg/artwork/experience/xp-urumci-on-cebeci-uygur-sofrasi/hero-v1/hero.svg",
      "Square": "svg/artwork/experience/xp-urumci-on-cebeci-uygur-sofrasi/hero-v1/square.svg",
      "Compact": "svg/artwork/experience/xp-urumci-on-cebeci-uygur-sofrasi/hero-v1/compact.svg"
    },
    "idea/active-movement/active-motion/v01": {
      "Hero": "svg/artwork/idea/active-movement/active-motion/v01/hero.svg",
      "Square": "svg/artwork/idea/active-movement/active-motion/v01/square.svg",
      "Compact": "svg/artwork/idea/active-movement/active-motion/v01/compact.svg"
    },
    "idea/active-movement/active-motion/v02": {
      "Hero": "svg/artwork/idea/active-movement/active-motion/v02/hero.svg",
      "Square": "svg/artwork/idea/active-movement/active-motion/v02/square.svg",
      "Compact": "svg/artwork/idea/active-movement/active-motion/v02/compact.svg"
    },
    "idea/coffee-drink-ritual/drink-ritual/v01": {
      "Hero": "svg/artwork/idea/coffee-drink-ritual/drink-ritual/v01/hero.svg",
      "Square": "svg/artwork/idea/coffee-drink-ritual/drink-ritual/v01/square.svg",
      "Compact": "svg/artwork/idea/coffee-drink-ritual/drink-ritual/v01/compact.svg"
    },
    "idea/coffee-drink-ritual/drink-ritual/v02": {
      "Hero": "svg/artwork/idea/coffee-drink-ritual/drink-ritual/v02/hero.svg",
      "Square": "svg/artwork/idea/coffee-drink-ritual/drink-ritual/v02/square.svg",
      "Compact": "svg/artwork/idea/coffee-drink-ritual/drink-ritual/v02/compact.svg"
    },
    "idea/creative-art/creative-tools/v01": {
      "Hero": "svg/artwork/idea/creative-art/creative-tools/v01/hero.svg",
      "Square": "svg/artwork/idea/creative-art/creative-tools/v01/square.svg",
      "Compact": "svg/artwork/idea/creative-art/creative-tools/v01/compact.svg"
    },
    "idea/creative-art/creative-tools/v02": {
      "Hero": "svg/artwork/idea/creative-art/creative-tools/v02/hero.svg",
      "Square": "svg/artwork/idea/creative-art/creative-tools/v02/square.svg",
      "Compact": "svg/artwork/idea/creative-art/creative-tools/v02/compact.svg"
    },
    "idea/curiosity-learning/learning-detail/v01": {
      "Hero": "svg/artwork/idea/curiosity-learning/learning-detail/v01/hero.svg",
      "Square": "svg/artwork/idea/curiosity-learning/learning-detail/v01/square.svg",
      "Compact": "svg/artwork/idea/curiosity-learning/learning-detail/v01/compact.svg"
    },
    "idea/curiosity-learning/learning-detail/v02": {
      "Hero": "svg/artwork/idea/curiosity-learning/learning-detail/v02/hero.svg",
      "Square": "svg/artwork/idea/curiosity-learning/learning-detail/v02/square.svg",
      "Compact": "svg/artwork/idea/curiosity-learning/learning-detail/v02/compact.svg"
    },
    "idea/food-cooking/hands-cooking/v01": {
      "Hero": "svg/artwork/idea/food-cooking/hands-cooking/v01/hero.svg",
      "Square": "svg/artwork/idea/food-cooking/hands-cooking/v01/square.svg",
      "Compact": "svg/artwork/idea/food-cooking/hands-cooking/v01/compact.svg"
    },
    "idea/food-cooking/hands-cooking/v02": {
      "Hero": "svg/artwork/idea/food-cooking/hands-cooking/v02/hero.svg",
      "Square": "svg/artwork/idea/food-cooking/hands-cooking/v02/square.svg",
      "Compact": "svg/artwork/idea/food-cooking/hands-cooking/v02/compact.svg"
    },
    "idea/friend-group/friends-activity/v01": {
      "Hero": "svg/artwork/idea/friend-group/friends-activity/v01/hero.svg",
      "Square": "svg/artwork/idea/friend-group/friends-activity/v01/square.svg",
      "Compact": "svg/artwork/idea/friend-group/friends-activity/v01/compact.svg"
    },
    "idea/friend-group/friends-activity/v02": {
      "Hero": "svg/artwork/idea/friend-group/friends-activity/v02/hero.svg",
      "Square": "svg/artwork/idea/friend-group/friends-activity/v02/square.svg",
      "Compact": "svg/artwork/idea/friend-group/friends-activity/v02/compact.svg"
    },
    "idea/home-bad-weather/cozy-home/v01": {
      "Hero": "svg/artwork/idea/home-bad-weather/cozy-home/v01/hero.svg",
      "Square": "svg/artwork/idea/home-bad-weather/cozy-home/v01/square.svg",
      "Compact": "svg/artwork/idea/home-bad-weather/cozy-home/v01/compact.svg"
    },
    "idea/home-bad-weather/cozy-home/v02": {
      "Hero": "svg/artwork/idea/home-bad-weather/cozy-home/v02/hero.svg",
      "Square": "svg/artwork/idea/home-bad-weather/cozy-home/v02/square.svg",
      "Compact": "svg/artwork/idea/home-bad-weather/cozy-home/v02/compact.svg"
    },
    "idea/micro-adventure/small-discovery/v01": {
      "Hero": "svg/artwork/idea/micro-adventure/small-discovery/v01/hero.svg",
      "Square": "svg/artwork/idea/micro-adventure/small-discovery/v01/square.svg",
      "Compact": "svg/artwork/idea/micro-adventure/small-discovery/v01/compact.svg"
    },
    "idea/micro-adventure/small-discovery/v02": {
      "Hero": "svg/artwork/idea/micro-adventure/small-discovery/v02/hero.svg",
      "Square": "svg/artwork/idea/micro-adventure/small-discovery/v02/square.svg",
      "Compact": "svg/artwork/idea/micro-adventure/small-discovery/v02/compact.svg"
    },
    "idea/outdoor-neighborhood/neighborhood-walk/v01": {
      "Hero": "svg/artwork/idea/outdoor-neighborhood/neighborhood-walk/v01/hero.svg",
      "Square": "svg/artwork/idea/outdoor-neighborhood/neighborhood-walk/v01/square.svg",
      "Compact": "svg/artwork/idea/outdoor-neighborhood/neighborhood-walk/v01/compact.svg"
    },
    "idea/outdoor-neighborhood/neighborhood-walk/v02": {
      "Hero": "svg/artwork/idea/outdoor-neighborhood/neighborhood-walk/v02/hero.svg",
      "Square": "svg/artwork/idea/outdoor-neighborhood/neighborhood-walk/v02/square.svg",
      "Compact": "svg/artwork/idea/outdoor-neighborhood/neighborhood-walk/v02/compact.svg"
    },
    "idea/pair-date/two-person-moment/v01": {
      "Hero": "svg/artwork/idea/pair-date/two-person-moment/v01/hero.svg",
      "Square": "svg/artwork/idea/pair-date/two-person-moment/v01/square.svg",
      "Compact": "svg/artwork/idea/pair-date/two-person-moment/v01/compact.svg"
    },
    "idea/pair-date/two-person-moment/v02": {
      "Hero": "svg/artwork/idea/pair-date/two-person-moment/v02/hero.svg",
      "Square": "svg/artwork/idea/pair-date/two-person-moment/v02/square.svg",
      "Compact": "svg/artwork/idea/pair-date/two-person-moment/v02/compact.svg"
    },
    "idea/social-ritual-hosting/shared-table/v01": {
      "Hero": "svg/artwork/idea/social-ritual-hosting/shared-table/v01/hero.svg",
      "Square": "svg/artwork/idea/social-ritual-hosting/shared-table/v01/square.svg",
      "Compact": "svg/artwork/idea/social-ritual-hosting/shared-table/v01/compact.svg"
    },
    "idea/social-ritual-hosting/shared-table/v02": {
      "Hero": "svg/artwork/idea/social-ritual-hosting/shared-table/v02/hero.svg",
      "Square": "svg/artwork/idea/social-ritual-hosting/shared-table/v02/square.svg",
      "Compact": "svg/artwork/idea/social-ritual-hosting/shared-table/v02/compact.svg"
    },
    "idea/solo-reset/quiet-reset/v01": {
      "Hero": "svg/artwork/idea/solo-reset/quiet-reset/v01/hero.svg",
      "Square": "svg/artwork/idea/solo-reset/quiet-reset/v01/square.svg",
      "Compact": "svg/artwork/idea/solo-reset/quiet-reset/v01/compact.svg"
    },
    "idea/solo-reset/quiet-reset/v02": {
      "Hero": "svg/artwork/idea/solo-reset/quiet-reset/v02/hero.svg",
      "Square": "svg/artwork/idea/solo-reset/quiet-reset/v02/square.svg",
      "Compact": "svg/artwork/idea/solo-reset/quiet-reset/v02/compact.svg"
    },
    "place/active-sports/active-motion/v01": {
      "Hero": "svg/artwork/place/active-sports/active-motion/v01/hero.svg",
      "Square": "svg/artwork/place/active-sports/active-motion/v01/square.svg",
      "Compact": "svg/artwork/place/active-sports/active-motion/v01/compact.svg"
    },
    "place/activity-venue/venue-program/v01": {
      "Hero": "svg/artwork/place/activity-venue/venue-program/v01/hero.svg",
      "Square": "svg/artwork/place/activity-venue/venue-program/v01/square.svg",
      "Compact": "svg/artwork/place/activity-venue/venue-program/v01/compact.svg"
    },
    "place/aquarium-family/aquarium-tunnel/v01": {
      "Hero": "svg/artwork/place/aquarium-family/aquarium-tunnel/v01/hero.svg",
      "Square": "svg/artwork/place/aquarium-family/aquarium-tunnel/v01/square.svg",
      "Compact": "svg/artwork/place/aquarium-family/aquarium-tunnel/v01/compact.svg"
    },
    "place/bakery-local/bakery-detail/v01": {
      "Hero": "svg/artwork/place/bakery-local/bakery-detail/v01/hero.svg",
      "Square": "svg/artwork/place/bakery-local/bakery-detail/v01/square.svg",
      "Compact": "svg/artwork/place/bakery-local/bakery-detail/v01/compact.svg"
    },
    "place/bar-nightlife/social-night/v01": {
      "Hero": "svg/artwork/place/bar-nightlife/social-night/v01/hero.svg",
      "Square": "svg/artwork/place/bar-nightlife/social-night/v01/square.svg",
      "Compact": "svg/artwork/place/bar-nightlife/social-night/v01/compact.svg"
    },
    "place/cafe-social/cafe-interior/v01": {
      "Hero": "svg/artwork/place/cafe-social/cafe-interior/v01/hero.svg",
      "Square": "svg/artwork/place/cafe-social/cafe-interior/v01/square.svg",
      "Compact": "svg/artwork/place/cafe-social/cafe-interior/v01/compact.svg"
    },
    "place/cafe-social/cafe-interior/v02": {
      "Hero": "svg/artwork/place/cafe-social/cafe-interior/v02/hero.svg",
      "Square": "svg/artwork/place/cafe-social/cafe-interior/v02/square.svg",
      "Compact": "svg/artwork/place/cafe-social/cafe-interior/v02/compact.svg"
    },
    "place/cinema-screening/cinema-screen/v01": {
      "Hero": "svg/artwork/place/cinema-screening/cinema-screen/v01/hero.svg",
      "Square": "svg/artwork/place/cinema-screening/cinema-screen/v01/square.svg",
      "Compact": "svg/artwork/place/cinema-screening/cinema-screen/v01/compact.svg"
    },
    "place/city-attraction/city-view/v01": {
      "Hero": "svg/artwork/place/city-attraction/city-view/v01/hero.svg",
      "Square": "svg/artwork/place/city-attraction/city-view/v01/square.svg",
      "Compact": "svg/artwork/place/city-attraction/city-view/v01/compact.svg"
    },
    "place/creative-workshop/hands-making/v01": {
      "Hero": "svg/artwork/place/creative-workshop/hands-making/v01/hero.svg",
      "Square": "svg/artwork/place/creative-workshop/hands-making/v01/square.svg",
      "Compact": "svg/artwork/place/creative-workshop/hands-making/v01/compact.svg"
    },
    "place/culinary-workshop/hands-cooking/v01": {
      "Hero": "svg/artwork/place/culinary-workshop/hands-cooking/v01/hero.svg",
      "Square": "svg/artwork/place/culinary-workshop/hands-cooking/v01/square.svg",
      "Compact": "svg/artwork/place/culinary-workshop/hands-cooking/v01/compact.svg"
    },
    "place/culture-space/culture-interior/v01": {
      "Hero": "svg/artwork/place/culture-space/culture-interior/v01/hero.svg",
      "Square": "svg/artwork/place/culture-space/culture-interior/v01/square.svg",
      "Compact": "svg/artwork/place/culture-space/culture-interior/v01/compact.svg"
    },
    "place/destination-dining/dining-atmosphere/v01": {
      "Hero": "svg/artwork/place/destination-dining/dining-atmosphere/v01/hero.svg",
      "Square": "svg/artwork/place/destination-dining/dining-atmosphere/v01/square.svg",
      "Compact": "svg/artwork/place/destination-dining/dining-atmosphere/v01/compact.svg"
    },
    "place/forest-hiking/forest-trail/v01": {
      "Hero": "svg/artwork/place/forest-hiking/forest-trail/v01/hero.svg",
      "Square": "svg/artwork/place/forest-hiking/forest-trail/v01/square.svg",
      "Compact": "svg/artwork/place/forest-hiking/forest-trail/v01/compact.svg"
    },
    "place/games-social/tabletop-play/v01": {
      "Hero": "svg/artwork/place/games-social/tabletop-play/v01/hero.svg",
      "Square": "svg/artwork/place/games-social/tabletop-play/v01/square.svg",
      "Compact": "svg/artwork/place/games-social/tabletop-play/v01/compact.svg"
    },
    "place/heritage-district/historic-street/v01": {
      "Hero": "svg/artwork/place/heritage-district/historic-street/v01/hero.svg",
      "Square": "svg/artwork/place/heritage-district/historic-street/v01/square.svg",
      "Compact": "svg/artwork/place/heritage-district/historic-street/v01/compact.svg"
    },
    "place/heritage-landmark/heritage-architecture/v01": {
      "Hero": "svg/artwork/place/heritage-landmark/heritage-architecture/v01/hero.svg",
      "Square": "svg/artwork/place/heritage-landmark/heritage-architecture/v01/square.svg",
      "Compact": "svg/artwork/place/heritage-landmark/heritage-architecture/v01/compact.svg"
    },
    "place/heritage-landmark/heritage-architecture/v02": {
      "Hero": "svg/artwork/place/heritage-landmark/heritage-architecture/v02/hero.svg",
      "Square": "svg/artwork/place/heritage-landmark/heritage-architecture/v02/square.svg",
      "Compact": "svg/artwork/place/heritage-landmark/heritage-architecture/v02/compact.svg"
    },
    "place/lake-waterfront/waterfront/v01": {
      "Hero": "svg/artwork/place/lake-waterfront/waterfront/v01/hero.svg",
      "Square": "svg/artwork/place/lake-waterfront/waterfront/v01/square.svg",
      "Compact": "svg/artwork/place/lake-waterfront/waterfront/v01/compact.svg"
    },
    "place/lake-waterfront/waterfront/v02": {
      "Hero": "svg/artwork/place/lake-waterfront/waterfront/v02/hero.svg",
      "Square": "svg/artwork/place/lake-waterfront/waterfront/v02/square.svg",
      "Compact": "svg/artwork/place/lake-waterfront/waterfront/v02/compact.svg"
    },
    "place/library-bookstore/books-culture/v01": {
      "Hero": "svg/artwork/place/library-bookstore/books-culture/v01/hero.svg",
      "Square": "svg/artwork/place/library-bookstore/books-culture/v01/square.svg",
      "Compact": "svg/artwork/place/library-bookstore/books-culture/v01/compact.svg"
    },
    "place/live-music/concert-stage/v01": {
      "Hero": "svg/artwork/place/live-music/concert-stage/v01/hero.svg",
      "Square": "svg/artwork/place/live-music/concert-stage/v01/square.svg",
      "Compact": "svg/artwork/place/live-music/concert-stage/v01/compact.svg"
    },
    "place/local-restaurant/local-food-table/v01": {
      "Hero": "svg/artwork/place/local-restaurant/local-food-table/v01/hero.svg",
      "Square": "svg/artwork/place/local-restaurant/local-food-table/v01/square.svg",
      "Compact": "svg/artwork/place/local-restaurant/local-food-table/v01/compact.svg"
    },
    "place/local-restaurant/local-food-table/v02": {
      "Hero": "svg/artwork/place/local-restaurant/local-food-table/v02/hero.svg",
      "Square": "svg/artwork/place/local-restaurant/local-food-table/v02/square.svg",
      "Compact": "svg/artwork/place/local-restaurant/local-food-table/v02/compact.svg"
    },
    "place/museum-gallery/museum-gallery/v01": {
      "Hero": "svg/artwork/place/museum-gallery/museum-gallery/v01/hero.svg",
      "Square": "svg/artwork/place/museum-gallery/museum-gallery/v01/square.svg",
      "Compact": "svg/artwork/place/museum-gallery/museum-gallery/v01/compact.svg"
    },
    "place/museum-gallery/museum-gallery/v02": {
      "Hero": "svg/artwork/place/museum-gallery/museum-gallery/v02/hero.svg",
      "Square": "svg/artwork/place/museum-gallery/museum-gallery/v02/square.svg",
      "Compact": "svg/artwork/place/museum-gallery/museum-gallery/v02/compact.svg"
    },
    "place/museum-gallery/museum-gallery/v03": {
      "Hero": "svg/artwork/place/museum-gallery/museum-gallery/v03/hero.svg",
      "Square": "svg/artwork/place/museum-gallery/museum-gallery/v03/square.svg",
      "Compact": "svg/artwork/place/museum-gallery/museum-gallery/v03/compact.svg"
    },
    "place/museum-gallery/museum-gallery/v04": {
      "Hero": "svg/artwork/place/museum-gallery/museum-gallery/v04/hero.svg",
      "Square": "svg/artwork/place/museum-gallery/museum-gallery/v04/square.svg",
      "Compact": "svg/artwork/place/museum-gallery/museum-gallery/v04/compact.svg"
    },
    "place/outdoor-walk/walking-landscape/v01": {
      "Hero": "svg/artwork/place/outdoor-walk/walking-landscape/v01/hero.svg",
      "Square": "svg/artwork/place/outdoor-walk/walking-landscape/v01/square.svg",
      "Compact": "svg/artwork/place/outdoor-walk/walking-landscape/v01/compact.svg"
    },
    "place/performance-stage/theatre-stage/v01": {
      "Hero": "svg/artwork/place/performance-stage/theatre-stage/v01/hero.svg",
      "Square": "svg/artwork/place/performance-stage/theatre-stage/v01/square.svg",
      "Compact": "svg/artwork/place/performance-stage/theatre-stage/v01/compact.svg"
    },
    "place/performance-stage/theatre-stage/v02": {
      "Hero": "svg/artwork/place/performance-stage/theatre-stage/v02/hero.svg",
      "Square": "svg/artwork/place/performance-stage/theatre-stage/v02/square.svg",
      "Compact": "svg/artwork/place/performance-stage/theatre-stage/v02/compact.svg"
    },
    "place/scenic-nature/landscape-detail/v01": {
      "Hero": "svg/artwork/place/scenic-nature/landscape-detail/v01/hero.svg",
      "Square": "svg/artwork/place/scenic-nature/landscape-detail/v01/square.svg",
      "Compact": "svg/artwork/place/scenic-nature/landscape-detail/v01/compact.svg"
    },
    "place/science-interactive/science-exhibit/v01": {
      "Hero": "svg/artwork/place/science-interactive/science-exhibit/v01/hero.svg",
      "Square": "svg/artwork/place/science-interactive/science-exhibit/v01/square.svg",
      "Compact": "svg/artwork/place/science-interactive/science-exhibit/v01/compact.svg"
    },
    "place/specialty-coffee/coffee-detail/v01": {
      "Hero": "svg/artwork/place/specialty-coffee/coffee-detail/v01/hero.svg",
      "Square": "svg/artwork/place/specialty-coffee/coffee-detail/v01/square.svg",
      "Compact": "svg/artwork/place/specialty-coffee/coffee-detail/v01/compact.svg"
    },
    "place/specialty-coffee/coffee-detail/v02": {
      "Hero": "svg/artwork/place/specialty-coffee/coffee-detail/v02/hero.svg",
      "Square": "svg/artwork/place/specialty-coffee/coffee-detail/v02/square.svg",
      "Compact": "svg/artwork/place/specialty-coffee/coffee-detail/v02/compact.svg"
    },
    "place/urban-park/urban-green/v01": {
      "Hero": "svg/artwork/place/urban-park/urban-green/v01/hero.svg",
      "Square": "svg/artwork/place/urban-park/urban-green/v01/square.svg",
      "Compact": "svg/artwork/place/urban-park/urban-green/v01/compact.svg"
    },
    "place/urban-park/urban-green/v02": {
      "Hero": "svg/artwork/place/urban-park/urban-green/v02/hero.svg",
      "Square": "svg/artwork/place/urban-park/urban-green/v02/square.svg",
      "Compact": "svg/artwork/place/urban-park/urban-green/v02/compact.svg"
    }
  },
  "icons": {
    "icon/event/family": "svg/icons/icon/event/family.svg",
    "icon/event/festival": "svg/icons/icon/event/festival.svg",
    "icon/event/film": "svg/icons/icon/event/film.svg",
    "icon/event/game": "svg/icons/icon/event/game.svg",
    "icon/event/music": "svg/icons/icon/event/music.svg",
    "icon/event/sport": "svg/icons/icon/event/sport.svg",
    "icon/event/stage": "svg/icons/icon/event/stage.svg",
    "icon/event/workshop": "svg/icons/icon/event/workshop.svg",
    "icon/experience/route-active": "svg/icons/icon/experience/route-active.svg",
    "icon/experience/route-culture": "svg/icons/icon/experience/route-culture.svg",
    "icon/experience/route-food": "svg/icons/icon/experience/route-food.svg",
    "icon/experience/route-nature": "svg/icons/icon/experience/route-nature.svg",
    "icon/idea/adventure": "svg/icons/icon/idea/adventure.svg",
    "icon/idea/coffee": "svg/icons/icon/idea/coffee.svg",
    "icon/idea/cooking": "svg/icons/icon/idea/cooking.svg",
    "icon/idea/creative": "svg/icons/icon/idea/creative.svg",
    "icon/idea/group": "svg/icons/icon/idea/group.svg",
    "icon/idea/home": "svg/icons/icon/idea/home.svg",
    "icon/idea/hosting": "svg/icons/icon/idea/hosting.svg",
    "icon/idea/learning": "svg/icons/icon/idea/learning.svg",
    "icon/idea/pair": "svg/icons/icon/idea/pair.svg",
    "icon/idea/self-care": "svg/icons/icon/idea/self-care.svg",
    "icon/idea/sport": "svg/icons/icon/idea/sport.svg",
    "icon/idea/walk": "svg/icons/icon/idea/walk.svg",
    "icon/place/aquarium": "svg/icons/icon/place/aquarium.svg",
    "icon/place/attraction": "svg/icons/icon/place/attraction.svg",
    "icon/place/bakery": "svg/icons/icon/place/bakery.svg",
    "icon/place/book": "svg/icons/icon/place/book.svg",
    "icon/place/coffee": "svg/icons/icon/place/coffee.svg",
    "icon/place/culture": "svg/icons/icon/place/culture.svg",
    "icon/place/film": "svg/icons/icon/place/film.svg",
    "icon/place/forest": "svg/icons/icon/place/forest.svg",
    "icon/place/game": "svg/icons/icon/place/game.svg",
    "icon/place/landmark": "svg/icons/icon/place/landmark.svg",
    "icon/place/museum": "svg/icons/icon/place/museum.svg",
    "icon/place/music": "svg/icons/icon/place/music.svg",
    "icon/place/nature": "svg/icons/icon/place/nature.svg",
    "icon/place/nightlife": "svg/icons/icon/place/nightlife.svg",
    "icon/place/park": "svg/icons/icon/place/park.svg",
    "icon/place/restaurant": "svg/icons/icon/place/restaurant.svg",
    "icon/place/science": "svg/icons/icon/place/science.svg",
    "icon/place/sport": "svg/icons/icon/place/sport.svg",
    "icon/place/stage": "svg/icons/icon/place/stage.svg",
    "icon/place/ticket": "svg/icons/icon/place/ticket.svg",
    "icon/place/water": "svg/icons/icon/place/water.svg",
    "icon/place/workshop": "svg/icons/icon/place/workshop.svg"
  },
  "ui": {
    "saveDefault": "svg/ui/saveDefault.svg",
    "savePressed": "svg/ui/savePressed.svg",
    "saveSaved": "svg/ui/saveSaved.svg",
    "dismissDefault": "svg/ui/dismissDefault.svg",
    "dismissPressed": "svg/ui/dismissPressed.svg",
    "dismissLoading": "svg/ui/dismissLoading.svg",
    "dismissDismissed": "svg/ui/dismissDismissed.svg",
    "discoveryPlace": "svg/ui/discoveryPlace.svg",
    "discoveryEvent": "svg/ui/discoveryEvent.svg",
    "discoveryIdea": "svg/ui/discoveryIdea.svg",
    "discoveryExperience": "svg/ui/discoveryExperience.svg"
  },
  "content": {
    "event:event-ajda-pekkan-oran-2026-09-30": {
      "artwork_key": "event/concert-live/v01",
      "icon_key": "icon/event/music"
    },
    "event:event-amadeus-congresium-2026-10-16": {
      "artwork_key": "event/theatre-play/v01",
      "icon_key": "icon/event/stage"
    },
    "event:event-ankara-cocktail-festival-2026-09-27": {
      "artwork_key": "event/festival-food-drink/v01",
      "icon_key": "icon/event/festival"
    },
    "event:event-ankara-open-wta-125-2026-09-22": {
      "artwork_key": "event/sports-event/v01",
      "icon_key": "icon/event/sport"
    },
    "event:event-bubble-show-cukurambar-2026-10-03": {
      "artwork_key": "event/family-show/v01",
      "icon_key": "icon/event/family"
    },
    "event:event-candles-echoes-meb-sura-2026-09-26": {
      "artwork_key": "event/concert-classical-acoustic/v01",
      "icon_key": "icon/event/music"
    },
    "event:event-golden-chef-el-yapimi-makarnalar-2026-09-29": {
      "artwork_key": "event/culinary-workshop/v01",
      "icon_key": "icon/event/workshop"
    },
    "event:event-happy-pigs-cayyolu-2026-09-27": {
      "artwork_key": "event/theatre-play/v01",
      "icon_key": "icon/event/stage"
    },
    "event:event-masumiyet-demirkubuz-visnelik-2026-09-23": {
      "artwork_key": "event/film-talk/v01",
      "icon_key": "icon/event/film"
    },
    "event:event-one-more-atilim-2026-09-24": {
      "artwork_key": "event/theatre-play/v01",
      "icon_key": "icon/event/stage"
    },
    "event:event-sami-yusuf-congresium-2026-09-24": {
      "artwork_key": "event/concert-classical-acoustic/v01",
      "icon_key": "icon/event/music"
    },
    "event:event-tastydays-visnelik-2026-10-11": {
      "artwork_key": "event/concert-live/v01",
      "icon_key": "icon/event/music"
    },
    "event:event-tca-burger-fries-workshop-2026-09-24": {
      "artwork_key": "event/culinary-workshop/v01",
      "icon_key": "icon/event/workshop"
    },
    "event:event-trivia-night-alti-ustu-2026-09-26": {
      "artwork_key": "event/trivia-games/v01",
      "icon_key": "icon/event/game"
    },
    "experience:xp-altinkoy-koy-yasamini-uc-izden-oku": {
      "artwork_key": "experience/xp-altinkoy-koy-yasamini-uc-izden-oku/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-altinpark-uzun-ogleden-sonra": {
      "artwork_key": "experience/xp-altinpark-uzun-ogleden-sonra/hero-v1",
      "icon_key": "icon/experience/route-nature"
    },
    "experience:xp-anadolu-kronolojik": {
      "artwork_key": "experience/xp-anadolu-kronolojik/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-anitkabir-maltepe": {
      "artwork_key": "experience/xp-anitkabir-maltepe/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-ankara-palas-ikinci-tbmm": {
      "artwork_key": "experience/xp-ankara-palas-ikinci-tbmm/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-aoc-kurulus-hikayesi": {
      "artwork_key": "experience/xp-aoc-kurulus-hikayesi/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-aqua-vega-uc-yasam-alani": {
      "artwork_key": "experience/xp-aqua-vega-uc-yasam-alani/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-arslanhane-alaaddin-selcuklu": {
      "artwork_key": "experience/xp-arslanhane-alaaddin-selcuklu/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-aspava-ikram-ritueli": {
      "artwork_key": "experience/xp-aspava-ikram-ritueli/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-beypazari-halfday": {
      "artwork_key": "experience/xp-beypazari-halfday/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-bogazici-ulus-ogle-ritueli": {
      "artwork_key": "experience/xp-bogazici-ulus-ogle-ritueli/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-bolu-akin-eski-garajlar-tencere": {
      "artwork_key": "experience/xp-bolu-akin-eski-garajlar-tencere/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-botanik-atakule-short": {
      "artwork_key": "experience/xp-botanik-atakule-short/hero-v1",
      "icon_key": "icon/experience/route-nature"
    },
    "experience:xp-cengelhan-teknolojinin-izini-sur": {
      "artwork_key": "experience/xp-cengelhan-teknolojinin-izini-sur/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-cin-ali-iki-kusak": {
      "artwork_key": "experience/xp-cin-ali-iki-kusak/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-cubuk-1-baraji-muhendislik-gozu": {
      "artwork_key": "experience/xp-cubuk-1-baraji-muhendislik-gozu/hero-v1",
      "icon_key": "icon/experience/route-nature"
    },
    "experience:xp-da-vinci-yeni-oyun": {
      "artwork_key": "experience/xp-da-vinci-yeni-oyun/hero-v1",
      "icon_key": "icon/experience/route-active"
    },
    "experience:xp-dikmen-vadisi-kot-yuruyusu": {
      "artwork_key": "experience/xp-dikmen-vadisi-kot-yuruyusu/hero-v1",
      "icon_key": "icon/experience/route-active"
    },
    "experience:xp-dost-konu-raf-haritasi": {
      "artwork_key": "experience/xp-dost-konu-raf-haritasi/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-duveroglu-lahmacun": {
      "artwork_key": "experience/xp-duveroglu-lahmacun/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-erimtan-kale": {
      "artwork_key": "experience/xp-erimtan-kale/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-etnografya-resim": {
      "artwork_key": "experience/xp-etnografya-resim/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-eymir-bisikletle-dolas": {
      "artwork_key": "experience/xp-eymir-bisikletle-dolas/hero-v1",
      "icon_key": "icon/experience/route-active"
    },
    "experience:xp-eymir-halfday": {
      "artwork_key": "experience/xp-eymir-halfday/hero-v1",
      "icon_key": "icon/experience/route-active"
    },
    "experience:xp-federal-bilkent-demleme": {
      "artwork_key": "experience/xp-federal-bilkent-demleme/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-goksu-loop": {
      "artwork_key": "experience/xp-goksu-loop/hero-v1",
      "icon_key": "icon/experience/route-active"
    },
    "experience:xp-gokyay-satranc-taslari": {
      "artwork_key": "experience/xp-gokyay-satranc-taslari/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-gordion-halfday": {
      "artwork_key": "experience/xp-gordion-halfday/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-hacibayram-augustus": {
      "artwork_key": "experience/xp-hacibayram-augustus/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-hanem-konya-sofrasi": {
      "artwork_key": "experience/xp-hanem-konya-sofrasi/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-hava-kuvvetleri-iki-saat": {
      "artwork_key": "experience/xp-hava-kuvvetleri-iki-saat/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-kecioren-cocuk-sanat-muzesi-rehber": {
      "artwork_key": "experience/xp-kecioren-cocuk-sanat-muzesi-rehber/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-kelime-erimtan-kale": {
      "artwork_key": "experience/xp-kelime-erimtan-kale/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-kitir-tunali-bulusma-hafizasi": {
      "artwork_key": "experience/xp-kitir-tunali-bulusma-hafizasi/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-kizilcahamam-halfday": {
      "artwork_key": "experience/xp-kizilcahamam-halfday/hero-v1",
      "icon_key": "icon/experience/route-nature"
    },
    "experience:xp-kugulu-segmenler": {
      "artwork_key": "experience/xp-kugulu-segmenler/hero-v1",
      "icon_key": "icon/experience/route-nature"
    },
    "experience:xp-mavi-gol-sehirden-uzak": {
      "artwork_key": "experience/xp-mavi-gol-sehirden-uzak/hero-v1",
      "icon_key": "icon/experience/route-nature"
    },
    "experience:xp-meclis-duo-short": {
      "artwork_key": "experience/xp-meclis-duo-short/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-millet-kutuphanesi-derin-calisma": {
      "artwork_key": "experience/xp-millet-kutuphanesi-derin-calisma/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-mogan-halfday": {
      "artwork_key": "experience/xp-mogan-halfday/hero-v1",
      "icon_key": "icon/experience/route-nature"
    },
    "experience:xp-no29-kahve-tatli": {
      "artwork_key": "experience/xp-no29-kahve-tatli/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-odtu-double-museum": {
      "artwork_key": "experience/xp-odtu-double-museum/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-old-school-iki-demleme": {
      "artwork_key": "experience/xp-old-school-iki-demleme/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-pecenek-iskitler-doner-ritueli": {
      "artwork_key": "experience/xp-pecenek-iskitler-doner-ritueli/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-ptt-pullardan-donem-oku": {
      "artwork_key": "experience/xp-ptt-pullardan-donem-oku/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-roma-meclis": {
      "artwork_key": "experience/xp-roma-meclis/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-sakarya-muharebesini-araziden-oku": {
      "artwork_key": "experience/xp-sakarya-muharebesini-araziden-oku/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-tragos-tanitim-dersi": {
      "artwork_key": "experience/xp-tragos-tanitim-dersi/hero-v1",
      "icon_key": "icon/experience/route-active"
    },
    "experience:xp-trilye-balik": {
      "artwork_key": "experience/xp-trilye-balik/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-tunali-kugulu-short": {
      "artwork_key": "experience/xp-tunali-kugulu-short/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "experience:xp-ulucanlar-hamamonu": {
      "artwork_key": "experience/xp-ulucanlar-hamamonu/hero-v1",
      "icon_key": "icon/experience/route-culture"
    },
    "experience:xp-urumci-on-cebeci-uygur-sofrasi": {
      "artwork_key": "experience/xp-urumci-on-cebeci-uygur-sofrasi/hero-v1",
      "icon_key": "icon/experience/route-food"
    },
    "idea:idea-10k-route": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-30-min-drawing": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-aeropress": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-album-cover": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-audiobook-hands-busy": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v01",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-before-sunrise": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v01",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-bench-observation-notes": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v01",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-blind-snack": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-boardgame-arena": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-book-swap-note": {
      "artwork_key": "idea/friend-group/friends-activity/v01",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-breakfast-for-dinner": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-cafe-scorecard": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-chess-puzzle": {
      "artwork_key": "idea/micro-adventure/small-discovery/v02",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-childhood-photo-story": {
      "artwork_key": "idea/pair-date/two-person-moment/v02",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-clothing-accessory-swap": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v02",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-cloudspotting": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-coffee-playlist": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v01",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-coffee-temperature-tasting": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-coffee-wheel": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v01",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-dance-tutorial": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-dawn-neighborhood-walk": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v02",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-decade-karaoke": {
      "artwork_key": "idea/friend-group/friends-activity/v02",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-documentary-map-tracking": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-dumpling-night": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-earthcam": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-escape-puzzle": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-evening-caffeine-free-infusions": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-everyday-object-origin": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-family-oral-history": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v02",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-family-recipe-together": {
      "artwork_key": "idea/pair-date/two-person-moment/v02",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-floor-picnic-for-two": {
      "artwork_key": "idea/pair-date/two-person-moment/v02",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-forgotten-object-story": {
      "artwork_key": "idea/solo-reset/quiet-reset/v02",
      "icon_key": "icon/idea/self-care"
    },
    "idea:idea-found-object-still-life": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-free-dance-break": {
      "artwork_key": "idea/active-movement/active-motion/v01",
      "icon_key": "icon/idea/sport"
    },
    "idea:idea-geocaching": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v02",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-geoguessr": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-google-arts": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-grand-budapest": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-group-clothing-mend": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v01",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-hand-copy-poem": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-handwritten-letter": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v02",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-hourly-weather-observation": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-house-spice-blend": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-iced-coffee": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-inaturalist": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v01",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-internet-archive": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-jump-rope-rounds": {
      "artwork_key": "idea/active-movement/active-motion/v01",
      "icon_key": "icon/idea/sport"
    },
    "idea:idea-kitchen-herb-corner": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v01",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-koyaanisqatsi": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-leaf-bark-rubbings": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-leftovers-small-plates": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-lemonade-balance": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v01",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-letterboxd-roulette": {
      "artwork_key": "idea/micro-adventure/small-discovery/v02",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-memory-map-walk": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-memory-observation-drawing": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-merlin-bird": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-mobility-flow": {
      "artwork_key": "idea/active-movement/active-motion/v02",
      "icon_key": "icon/idea/sport"
    },
    "idea:idea-movie-soundtrack-walk": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-mubi-list": {
      "artwork_key": "idea/micro-adventure/small-discovery/v02",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-nasa-image": {
      "artwork_key": "idea/pair-date/two-person-moment/v02",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-neighborhood-architecture-details": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v01",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-neighborhood-micro-route": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-neighborhood-type-collection": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-night-sky": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-npr-tiny-desk": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-object-museum-label": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-omelette-master": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-one-dish-country": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-one-ingredient-small-plates": {
      "artwork_key": "idea/friend-group/friends-activity/v02",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-one-ingredient-two-methods": {
      "artwork_key": "idea/pair-date/two-person-moment/v01",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-one-item-each-picnic": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v01",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-one-minute-sound-collage": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-one-page-scene": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-one-page-zine": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-original-and-cover-listening": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-overnight-cold-brew": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-packaging-postcard": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-pantry-challenge": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-paper-plane": {
      "artwork_key": "idea/micro-adventure/small-discovery/v02",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-passage-exchange": {
      "artwork_key": "idea/pair-date/two-person-moment/v01",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-pasta-two-sauces": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-phone-free-topic-walk": {
      "artwork_key": "idea/pair-date/two-person-moment/v02",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-photo-archive-month": {
      "artwork_key": "idea/solo-reset/quiet-reset/v02",
      "icon_key": "icon/idea/self-care"
    },
    "idea:idea-photo-color-walk": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-photo-scavenger": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-pizza-hydration": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-plant-propagation": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v02",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-podcast-walk": {
      "artwork_key": "idea/active-movement/active-motion/v02",
      "icon_key": "icon/idea/sport"
    },
    "idea:idea-poetry-voice": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-puzzle-with-one-album": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v02",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-quick-flatbread": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-radio-garden": {
      "artwork_key": "idea/micro-adventure/small-discovery/v02",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-rain-window-sketches": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-reading-corner-hour": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v02",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-reading-light-comparison": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-remote-parallel-recipe": {
      "artwork_key": "idea/pair-date/two-person-moment/v02",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-repair-one-object": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v01",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-room-light-corner": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v01",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-salad-dressing-balance": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-same-view-two-angles": {
      "artwork_key": "idea/pair-date/two-person-moment/v01",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-seasonal-dinner-menu": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v01",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-seasonal-market-ingredient": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-shadow-tracing": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-shared-recipe-book-first-page": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v01",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-short-story-hot-drink": {
      "artwork_key": "idea/solo-reset/quiet-reset/v01",
      "icon_key": "icon/idea/self-care"
    },
    "idea:idea-signature-soft-drink": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-six-panel-day-comic": {
      "artwork_key": "idea/creative-art/creative-tools/v01",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-skill-swap": {
      "artwork_key": "idea/friend-group/friends-activity/v02",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-slow-bread-day": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-song-chain": {
      "artwork_key": "idea/friend-group/friends-activity/v01",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-sound-map": {
      "artwork_key": "idea/solo-reset/quiet-reset/v02",
      "icon_key": "icon/idea/self-care"
    },
    "idea:idea-soup-bread-table": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v01",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-speedrun-skill": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-spiced-hot-chocolate": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-stair-session": {
      "artwork_key": "idea/micro-adventure/small-discovery/v02",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-step-count-explore": {
      "artwork_key": "idea/friend-group/friends-activity/v02",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-story-food-potluck": {
      "artwork_key": "idea/social-ritual-hosting/shared-table/v01",
      "icon_key": "icon/idea/hosting"
    },
    "idea:idea-street-name-trail": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-stromae-racine-carree": {
      "artwork_key": "idea/creative-art/creative-tools/v02",
      "icon_key": "icon/idea/creative"
    },
    "idea:idea-sunset-map": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v01",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-tea-comparison": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v01",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-ten-phrases-mini-dialogue": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-thermos-coffee-walk": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v01",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-thermos-outdoor-reading": {
      "artwork_key": "idea/outdoor-neighborhood/neighborhood-walk/v02",
      "icon_key": "icon/idea/walk"
    },
    "idea:idea-three-new-outfits": {
      "artwork_key": "idea/home-bad-weather/cozy-home/v02",
      "icon_key": "icon/idea/home"
    },
    "idea:idea-three-object-home-exhibit": {
      "artwork_key": "idea/friend-group/friends-activity/v01",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-three-pace-walk": {
      "artwork_key": "idea/active-movement/active-motion/v02",
      "icon_key": "icon/idea/sport"
    },
    "idea:idea-three-photo-shared-fiction": {
      "artwork_key": "idea/friend-group/friends-activity/v01",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-three-song-exchange": {
      "artwork_key": "idea/pair-date/two-person-moment/v02",
      "icon_key": "icon/idea/pair"
    },
    "idea:idea-three-spreads-table": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-three-vegetable-soup": {
      "artwork_key": "idea/food-cooking/hands-cooking/v02",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-timed-bike-route": {
      "artwork_key": "idea/active-movement/active-motion/v01",
      "icon_key": "icon/idea/sport"
    },
    "idea:idea-trivia-night": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v02",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-turkish-coffee-variable": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v02",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-two-spice-comparison": {
      "artwork_key": "idea/food-cooking/hands-cooking/v01",
      "icon_key": "icon/idea/cooking"
    },
    "idea:idea-two-stops-early": {
      "artwork_key": "idea/micro-adventure/small-discovery/v01",
      "icon_key": "icon/idea/adventure"
    },
    "idea:idea-v60-comparison": {
      "artwork_key": "idea/coffee-drink-ritual/drink-ritual/v01",
      "icon_key": "icon/idea/coffee"
    },
    "idea:idea-wikipedia-race": {
      "artwork_key": "idea/friend-group/friends-activity/v02",
      "icon_key": "icon/idea/group"
    },
    "idea:idea-world-breakfast": {
      "artwork_key": "idea/curiosity-learning/learning-detail/v01",
      "icon_key": "icon/idea/learning"
    },
    "idea:idea-yoga-balance": {
      "artwork_key": "idea/micro-adventure/small-discovery/v02",
      "icon_key": "icon/idea/adventure"
    },
    "place:ahlatlibel-ataturk-parki": {
      "artwork_key": "place/forest-hiking/forest-trail/v01",
      "icon_key": "icon/place/forest"
    },
    "place:ahmet-taner-kislali-parki": {
      "artwork_key": "place/lake-waterfront/waterfront/v02",
      "icon_key": "icon/place/water"
    },
    "place:akun-sahnesi": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:alaaddin-camii": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v01",
      "icon_key": "icon/place/landmark"
    },
    "place:altinkoy-acik-hava-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:altinpark": {
      "artwork_key": "place/lake-waterfront/waterfront/v01",
      "icon_key": "icon/place/water"
    },
    "place:alucdagi-tabiat": {
      "artwork_key": "place/forest-hiking/forest-trail/v01",
      "icon_key": "icon/place/forest"
    },
    "place:anadolu-medeniyetleri": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:anitkabir": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:ankara-kalesi": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v01",
      "icon_key": "icon/place/landmark"
    },
    "place:ankara-opera": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:ankara-oyuncak-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:ankara-palas-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:ankara-sanat-tiyatrosu": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:ankara-universitesi-botanik": {
      "artwork_key": "place/urban-park/urban-green/v02",
      "icon_key": "icon/place/park"
    },
    "place:ankarali-vakif": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:ansera-parki": {
      "artwork_key": "place/urban-park/urban-green/v02",
      "icon_key": "icon/place/park"
    },
    "place:aoç-hayvanat-bahcesi-alani": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:aqua-vega-akvaryum": {
      "artwork_key": "place/aquarium-family/aquarium-tunnel/v01",
      "icon_key": "icon/place/aquarium"
    },
    "place:arabica-bahceli-7": {
      "artwork_key": "place/cafe-social/cafe-interior/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-besevler": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-beysukent": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-cayyolu-dogan-tasdelen": {
      "artwork_key": "place/cafe-social/cafe-interior/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-cayyolu-dorapark": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-emek-8": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-farilya-100yil": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-hosdere": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-kizilay-konur": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-regnum-skytower": {
      "artwork_key": "place/cafe-social/cafe-interior/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-tepe-prime": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-tunali-bulten": {
      "artwork_key": "place/cafe-social/cafe-interior/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:arabica-yildiz-kule": {
      "artwork_key": "place/cafe-social/cafe-interior/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:aslanhane-camii": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v02",
      "icon_key": "icon/place/landmark"
    },
    "place:aspava-yildizevler": {
      "artwork_key": "place/local-restaurant/local-food-table/v02",
      "icon_key": "icon/place/restaurant"
    },
    "place:ast-bilkent-sahne": {
      "artwork_key": "place/performance-stage/theatre-stage/v02",
      "icon_key": "icon/place/stage"
    },
    "place:atakule": {
      "artwork_key": "place/destination-dining/dining-atmosphere/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:atakule-botanik-teleferik": {
      "artwork_key": "place/city-attraction/city-view/v01",
      "icon_key": "icon/place/attraction"
    },
    "place:ataturk-kultur-merkezi-millet-bahcesi": {
      "artwork_key": "place/urban-park/urban-green/v01",
      "icon_key": "icon/place/park"
    },
    "place:ataturk-orman-ciftligi": {
      "artwork_key": "place/forest-hiking/forest-trail/v01",
      "icon_key": "icon/place/forest"
    },
    "place:augustus-tapinagi": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v02",
      "icon_key": "icon/place/landmark"
    },
    "place:ayas-tarihi-kent": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v01",
      "icon_key": "icon/place/landmark"
    },
    "place:belpa-buz-pateni": {
      "artwork_key": "place/active-sports/active-motion/v01",
      "icon_key": "icon/place/sport"
    },
    "place:beynam-ormanlari": {
      "artwork_key": "place/forest-hiking/forest-trail/v01",
      "icon_key": "icon/place/forest"
    },
    "place:beypazari-kent-tarihi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:beypazari-tarihi-carsi": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:beypazari-yasayan-muze": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:big-chefs-atakule": {
      "artwork_key": "place/destination-dining/dining-atmosphere/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:bilkent-gol": {
      "artwork_key": "place/lake-waterfront/waterfront/v01",
      "icon_key": "icon/place/water"
    },
    "place:bilkent-konser": {
      "artwork_key": "place/live-music/concert-stage/v01",
      "icon_key": "icon/place/music"
    },
    "place:bogazici-lokantasi": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:bolu-akin-lokantasi-etlik": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:botanik-parki": {
      "artwork_key": "place/urban-park/urban-green/v02",
      "icon_key": "icon/place/park"
    },
    "place:buyulu-fener-kizilay": {
      "artwork_key": "place/cinema-screening/cinema-screen/v01",
      "icon_key": "icon/place/film"
    },
    "place:cagdas-sanatlar-merkezi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:camildere-doga-hayvan": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:camildere-terazi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:camkoru-tabiat": {
      "artwork_key": "place/forest-hiking/forest-trail/v01",
      "icon_key": "icon/place/forest"
    },
    "place:camli-kosk": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:cankaya-ataturk-muze-kosku": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:cankaya-dogan-tasdelen": {
      "artwork_key": "place/activity-venue/venue-program/v01",
      "icon_key": "icon/place/ticket"
    },
    "place:cengelhan-rahmi-koc": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:cer-modern": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:cer-modern-acik-hava": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:cin-ali-muzesi": {
      "artwork_key": "place/library-bookstore/books-culture/v01",
      "icon_key": "icon/place/book"
    },
    "place:coffee-lab-bilkent": {
      "artwork_key": "place/specialty-coffee/coffee-detail/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:coffee-lab-tunali": {
      "artwork_key": "place/specialty-coffee/coffee-detail/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:cso-ada": {
      "artwork_key": "place/live-music/concert-stage/v01",
      "icon_key": "icon/place/music"
    },
    "place:cubuk-1-baraji-rekreasyon-alani": {
      "artwork_key": "place/lake-waterfront/waterfront/v01",
      "icon_key": "icon/place/water"
    },
    "place:cubuk-karagol": {
      "artwork_key": "place/lake-waterfront/waterfront/v02",
      "icon_key": "icon/place/water"
    },
    "place:cubuk-sehir-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:cumhurbaskanligi-millet-kutuphanesi": {
      "artwork_key": "place/library-bookstore/books-culture/v01",
      "icon_key": "icon/place/book"
    },
    "place:cumhuriyet-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:da-vinci-board-game-neorama": {
      "artwork_key": "place/games-social/tabletop-play/v01",
      "icon_key": "icon/place/game"
    },
    "place:devlet-tiyatrolari": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:dikmen-vadisi": {
      "artwork_key": "place/scenic-nature/landscape-detail/v01",
      "icon_key": "icon/place/nature"
    },
    "place:divan-cukurhan": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:dost-kitabevi-karanfil": {
      "artwork_key": "place/library-bookstore/books-culture/v01",
      "icon_key": "icon/place/book"
    },
    "place:duatepe-aniti": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v02",
      "icon_key": "icon/place/landmark"
    },
    "place:duveroğlu": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:e-go-kart": {
      "artwork_key": "place/active-sports/active-motion/v01",
      "icon_key": "icon/place/sport"
    },
    "place:egriova-tabiat": {
      "artwork_key": "place/lake-waterfront/waterfront/v01",
      "icon_key": "icon/place/water"
    },
    "place:elmadag-kayak": {
      "artwork_key": "place/active-sports/active-motion/v01",
      "icon_key": "icon/place/sport"
    },
    "place:erimtan": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:etimesgut-korkut-ata": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:etnografya-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:eymir-golu": {
      "artwork_key": "place/lake-waterfront/waterfront/v02",
      "icon_key": "icon/place/water"
    },
    "place:federal-bilkent": {
      "artwork_key": "place/specialty-coffee/coffee-detail/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:feza-gursey": {
      "artwork_key": "place/science-interactive/science-exhibit/v01",
      "icon_key": "icon/place/science"
    },
    "place:galeri-siyah-beyaz": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:gavurkale": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v02",
      "icon_key": "icon/place/landmark"
    },
    "place:gazi-egitim-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:genclik-parki": {
      "artwork_key": "place/lake-waterfront/waterfront/v02",
      "icon_key": "icon/place/water"
    },
    "place:goethe-institut-ankara": {
      "artwork_key": "place/library-bookstore/books-culture/v01",
      "icon_key": "icon/place/book"
    },
    "place:goksu-parki": {
      "artwork_key": "place/lake-waterfront/waterfront/v02",
      "icon_key": "icon/place/water"
    },
    "place:gokyay-vakfi-satranc-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:golden-chef-mutfak-akademisi-cayyolu": {
      "artwork_key": "place/culinary-workshop/hands-cooking/v01",
      "icon_key": "icon/place/workshop"
    },
    "place:gordion-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:gudul-tarihi-evler": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v02",
      "icon_key": "icon/place/landmark"
    },
    "place:guvenpark-kizilay": {
      "artwork_key": "place/urban-park/urban-green/v02",
      "icon_key": "icon/place/park"
    },
    "place:haci-bayram-veli": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v01",
      "icon_key": "icon/place/landmark"
    },
    "place:hacibayram-kebap": {
      "artwork_key": "place/local-restaurant/local-food-table/v02",
      "icon_key": "icon/place/restaurant"
    },
    "place:hamamonu": {
      "artwork_key": "place/heritage-district/historic-street/v01",
      "icon_key": "icon/place/landmark"
    },
    "place:hanem-firin-eryaman": {
      "artwork_key": "place/bakery-local/bakery-detail/v01",
      "icon_key": "icon/place/bakery"
    },
    "place:harikalar-diyari": {
      "artwork_key": "place/urban-park/urban-green/v02",
      "icon_key": "icon/place/park"
    },
    "place:hava-kuvvetleri-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:inonu-vadisi": {
      "artwork_key": "place/scenic-nature/landscape-detail/v01",
      "icon_key": "icon/place/nature"
    },
    "place:institut-francais-ankara": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:is-bankasi-iktisadi-muze": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:jandarma-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:jolly-joker-ankara": {
      "artwork_key": "place/live-music/concert-stage/v01",
      "icon_key": "icon/place/music"
    },
    "place:ka-cinnah": {
      "artwork_key": "place/culture-space/culture-interior/v01",
      "icon_key": "icon/place/culture"
    },
    "place:kalecik-kalesi": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v02",
      "icon_key": "icon/place/landmark"
    },
    "place:kartaltepe-mehmetcik": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v01",
      "icon_key": "icon/place/landmark"
    },
    "place:kebap-49-tunali": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:kecioren-cocuk-sanat-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:kecioren-deniz-dunyasi": {
      "artwork_key": "place/aquarium-family/aquarium-tunnel/v01",
      "icon_key": "icon/place/aquarium"
    },
    "place:kelime-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:kitir-tunali": {
      "artwork_key": "place/bar-nightlife/social-night/v01",
      "icon_key": "icon/place/nightlife"
    },
    "place:kizilcahamam-jeopark": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:kronotrop-tunali": {
      "artwork_key": "place/specialty-coffee/coffee-detail/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:kugulu-park": {
      "artwork_key": "place/urban-park/urban-green/v02",
      "icon_key": "icon/place/park"
    },
    "place:kurtbogazi-baraji": {
      "artwork_key": "place/lake-waterfront/waterfront/v02",
      "icon_key": "icon/place/water"
    },
    "place:kurtulus-savasi-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:kus-cenneti": {
      "artwork_key": "place/scenic-nature/landscape-detail/v01",
      "icon_key": "icon/place/nature"
    },
    "place:lavanta-bahcesi": {
      "artwork_key": "place/scenic-nature/landscape-detail/v01",
      "icon_key": "icon/place/nature"
    },
    "place:lavare-sokak": {
      "artwork_key": "place/performance-stage/theatre-stage/v02",
      "icon_key": "icon/place/stage"
    },
    "place:louise-brasserie-lounge": {
      "artwork_key": "place/bar-nightlife/social-night/v01",
      "icon_key": "icon/place/nightlife"
    },
    "place:lozan-parki": {
      "artwork_key": "place/urban-park/urban-green/v01",
      "icon_key": "icon/place/park"
    },
    "place:mamak-aquapark": {
      "artwork_key": "place/active-sports/active-motion/v01",
      "icon_key": "icon/place/sport"
    },
    "place:mamak-fuzyon-bilim-merkezi": {
      "artwork_key": "place/science-interactive/science-exhibit/v01",
      "icon_key": "icon/place/science"
    },
    "place:mamak-kultur-merkezi": {
      "artwork_key": "place/live-music/concert-stage/v01",
      "icon_key": "icon/place/music"
    },
    "place:mavi-gol": {
      "artwork_key": "place/lake-waterfront/waterfront/v01",
      "icon_key": "icon/place/water"
    },
    "place:meteoroloji-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:midpoint-armada": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:mogan-parki": {
      "artwork_key": "place/lake-waterfront/waterfront/v01",
      "icon_key": "icon/place/water"
    },
    "place:mta-tabiat-tarihi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:mulkiyeliler-birligi-kafe-restoran": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:nallihan-kiz-tepesi": {
      "artwork_key": "place/scenic-nature/landscape-detail/v01",
      "icon_key": "icon/place/nature"
    },
    "place:nazim-hikmet-kultur-merkezi": {
      "artwork_key": "place/live-music/concert-stage/v01",
      "icon_key": "icon/place/music"
    },
    "place:niki-restaurant-ankara": {
      "artwork_key": "place/bar-nightlife/social-night/v01",
      "icon_key": "icon/place/nightlife"
    },
    "place:no24-studio-umitkoy": {
      "artwork_key": "place/creative-workshop/hands-making/v01",
      "icon_key": "icon/place/workshop"
    },
    "place:no29-dukkan-coffee": {
      "artwork_key": "place/specialty-coffee/coffee-detail/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:nursultan-nazarbayev-parki": {
      "artwork_key": "place/urban-park/urban-green/v01",
      "icon_key": "icon/place/park"
    },
    "place:nusr-et-ankara": {
      "artwork_key": "place/destination-dining/dining-atmosphere/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:odtu-arkeoloji": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:odtu-bilim-teknoloji": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:odtu-devir-yolu": {
      "artwork_key": "place/outdoor-walk/walking-landscape/v01",
      "icon_key": "icon/place/nature"
    },
    "place:old-school-roastery-bahcelievler": {
      "artwork_key": "place/specialty-coffee/coffee-detail/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:pecenek-doner-iskitler": {
      "artwork_key": "place/local-restaurant/local-food-table/v02",
      "icon_key": "icon/place/restaurant"
    },
    "place:pembe-kosk": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    },
    "place:portakal-cicegi-parki": {
      "artwork_key": "place/urban-park/urban-green/v01",
      "icon_key": "icon/place/park"
    },
    "place:ptt-pul-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:quick-china-cayyolu": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:resim-heykel": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:roma-hamami": {
      "artwork_key": "place/museum-gallery/museum-gallery/v03",
      "icon_key": "icon/place/museum"
    },
    "place:sahinler-tabiat": {
      "artwork_key": "place/forest-hiking/forest-trail/v01",
      "icon_key": "icon/place/forest"
    },
    "place:sakarya-zaferi-muzesi": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v02",
      "icon_key": "icon/place/landmark"
    },
    "place:segmenler-parki": {
      "artwork_key": "place/urban-park/urban-green/v01",
      "icon_key": "icon/place/park"
    },
    "place:sinasi-sahnesi": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:sincan-harikalar-buz": {
      "artwork_key": "place/performance-stage/theatre-stage/v02",
      "icon_key": "icon/place/stage"
    },
    "place:sincan-lale": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:soguksu-milli-parki": {
      "artwork_key": "place/forest-hiking/forest-trail/v01",
      "icon_key": "icon/place/forest"
    },
    "place:starbucks-arnold": {
      "artwork_key": "place/cafe-social/cafe-interior/v02",
      "icon_key": "icon/place/coffee"
    },
    "place:starbucks-tunali": {
      "artwork_key": "place/cafe-social/cafe-interior/v01",
      "icon_key": "icon/place/coffee"
    },
    "place:sulu-han": {
      "artwork_key": "place/heritage-landmark/heritage-architecture/v01",
      "icon_key": "icon/place/landmark"
    },
    "place:tatbikat-sahnesi": {
      "artwork_key": "place/performance-stage/theatre-stage/v01",
      "icon_key": "icon/place/stage"
    },
    "place:tavaci-recep": {
      "artwork_key": "place/local-restaurant/local-food-table/v02",
      "icon_key": "icon/place/restaurant"
    },
    "place:tragos-boulder-outdoor": {
      "artwork_key": "place/active-sports/active-motion/v01",
      "icon_key": "icon/place/sport"
    },
    "place:trilye": {
      "artwork_key": "place/destination-dining/dining-atmosphere/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:turk-hamami-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v02",
      "icon_key": "icon/place/museum"
    },
    "place:tuz-golu": {
      "artwork_key": "place/lake-waterfront/waterfront/v02",
      "icon_key": "icon/place/water"
    },
    "place:ulucanlar-cezaevi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v04",
      "icon_key": "icon/place/museum"
    },
    "place:umitkoy-gokkusagi": {
      "artwork_key": "place/scenic-nature/landscape-detail/v01",
      "icon_key": "icon/place/nature"
    },
    "place:urumci-uygur-restaurant-on-cebeci": {
      "artwork_key": "place/local-restaurant/local-food-table/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:yakacik-mesire": {
      "artwork_key": "place/outdoor-walk/walking-landscape/v01",
      "icon_key": "icon/place/nature"
    },
    "place:zafer-parki": {
      "artwork_key": "place/urban-park/urban-green/v02",
      "icon_key": "icon/place/park"
    },
    "place:zenger-pasa": {
      "artwork_key": "place/destination-dining/dining-atmosphere/v01",
      "icon_key": "icon/place/restaurant"
    },
    "place:ziraat-bankasi-muzesi": {
      "artwork_key": "place/museum-gallery/museum-gallery/v01",
      "icon_key": "icon/place/museum"
    }
  }
} as const;
