import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

// No network, title inference, or catalog mutation. Re-run after approved asset changes.
const root = 'assets/gezek/production';
const manifest = JSON.parse(readFileSync(join(root, 'asset-export-manifest.json'), 'utf8'));
const items = JSON.parse(readFileSync(join(root, 'figma-asset-manifest.json'), 'utf8')).items;
const verification = JSON.parse(readFileSync(join(root, 'figma-export-verification.json'), 'utf8'));
const dimensions = { Hero: [329, 100], Square: [112, 112], Compact: [89, 72] } as const;
const artwork: Record<string, Record<string, string>> = {};
const icons: Record<string, string> = {};
const xml: Record<string, { xml: string; width: number; height: number }> = {};
const hashes: Record<string, string> = {};
function read(path: string, width: number, height: number) {
  const content = readFileSync(join(root, path), 'utf8');
  const svgRoot = content.match(/<svg\b[^>]*>/)?.[0] ?? '';
  if (!svgRoot.includes(`width="${width}"`) || !svgRoot.includes(`height="${height}"`)) throw new Error(`Invalid dimensions: ${path}`);
  xml[path] = { xml: content, width, height };
  hashes[path] = createHash('sha256').update(content).digest('hex');
  return path;
}
for (const family of manifest.artwork) {
  if (artwork[family.artwork_key]) throw new Error(`Duplicate artwork_key: ${family.artwork_key}`);
  if (family.export_status === 'pending-figma-export') throw new Error(`Unverified preview: ${family.artwork_key}`);
  artwork[family.artwork_key] = {};
  for (const [layout, [w, h]] of Object.entries(dimensions)) artwork[family.artwork_key][layout] = read(family.layouts[layout], w, h);
}
for (const icon of manifest.icons) {
  if (icons[icon.icon_key]) throw new Error(`Duplicate icon_key: ${icon.icon_key}`);
  icons[icon.icon_key] = read(icon.path, 32, 32);
}
const ui: Record<string, string> = {};
for (const e of verification.ui) ui[e.key] = read(`svg/ui/${e.key}.svg`, e.width, e.height);
const content: Record<string, { artwork_key: string; icon_key: string }> = {};
for (const item of items) {
  const key = `${item.kind}:${item.id}`;
  if (content[key]) throw new Error(`Duplicate stable ID: ${key}`);
  if (!artwork[item.artwork_key] || !icons[item.icon_component_key]) throw new Error(`Missing mapping: ${key}`);
  content[key] = { artwork_key: item.artwork_key, icon_key: item.icon_component_key };
}
writeFileSync('src/components/gezek/productionAssetIndex.ts', `// Generated by scripts/buildGezekAssets.ts. Do not edit.\nexport const PRODUCTION_ASSET_INDEX = ${JSON.stringify({ artwork, icons, ui, content }, null, 2)} as const;\n`);
writeFileSync('src/components/gezek/productionAssetXml.ts', `// Generated from unmodified local SVG files by scripts/buildGezekAssets.ts.\nexport const PRODUCTION_ASSET_XML: Readonly<Record<string, { xml: string; width: number; height: number }>> = ${JSON.stringify(xml, null, 2)};\n`);
writeFileSync(join(root, 'asset-checksums.json'), JSON.stringify(hashes, null, 2) + '\n');
console.log({ contentRecords: items.length, artworkFamilies: Object.keys(artwork).length, responsiveVariants: Object.keys(artwork).length * 3, contextualIcons: Object.keys(icons).length, uiExports: Object.keys(ui).length });
